[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.88.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.88.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.88.0"

[context.branch-deploy.environment]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.88.0"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true